Rectellipse.FCMacro
I was still not able to directly push the changes.
=> Add metadata to Rectellipse.FCMacro

.github/PULL_REQUEST_TEMPLATE.md, README.md
I've added a Pull Request Template similar to FreeCAD/FreeCAD but customized for FreeCAD/FreeCAD-macros. This hopefully will orient users who want to submit their macros to this repo. 
Please review. Of course modifications are welcome. 
CC @galou 
Previews: 
* https://github.com/luzpaz/FreeCAD-macros/blob/README-and-pull-request-template/README.md  
* https://github.com/luzpaz/FreeCAD-macros/blob/README-and-pull-request-template/.github/PULL_REQUEST_TEMPLATE.md
=> [WIP] Modify README + add Pull Request Template

Sketcher/SketchUnmap.FCMacro
=> SketchUnmap macro creation

Sketcher/SketchUnmap.FCMacro, Sketcher/SketchUnmap.svg
=> [SketchUnmap] add icon file + icon link in metadata + versioning update

Utility/PlacementAbsolufy.FCMacro
=> PlacementAbsolufy macro creation

Information/SimpleProperties.FCMacro
=> SimpleProperties macro creation

Utility/FCTree2Ascii.FCMacro
=> [FCTree2Ascii] Original release

ObjectCreation/BoxCreator.FCMacro
Just a small change suggested by blueOcean in the FreeCAD forum
=> [BoxCreator] Do not close dialog after clicking Create Box

Utility/HighlightCommon.FCMacro
This update adds a few changes:
1) If nothing is selected, iterates over all items in the document
2) Filters items to "PartDesign::Body", so that we don't compare against things like origins, planes, and things with no volume
3) Applies global placements to the shapes, so that the intersections go against the transformed objects and not their initial position
---
=> [HighlightCommon] Updating to support transformed objects

Sketcher/SketcherFixAllPoints.FCMacro, Sketcher/SketcherFixAllPoints.svg
=> edi SketcherFixAllPoints macro and icon

Sketcher/SketcherOffset.FCMacro, Sketcher/SketcherOffset.svg
=> SketcherOffset V2 and bugfix

TechDraw/TechDrawTools.FCMacro, TechDraw/TechDrawTools.svg
=> add new macro TechDrawTools

ObjectCreation/AeroFoil.FCMacro
---
There was an issue with the newly added 'split' curve feature. It's been fixed now.
=> [AeroFoil v2] A bug fixed as pointed out by Zolko-123

Sketcher/SketcherOffset.FCMacro
=> Sketcher offset compatible with 0.20 and without redundant constraint

Information/GetGlobalPlacement.FCMacro
=> [GetGlobalPlacement] First version

TechDraw/TechDrawTools.FCMacro
=> [TechdrawTools] Make Window Title reflect ver no. automatically

ImportExport/ObjectsToPython.FCMacro
=> [ObjectsToPython] added new Sketcher features

ImportExport/Export2Slicer.FCMacro
Small fix for error displaying
=> [Export2Slicer] Make error more visible to users

TechDraw/TechDrawTools.FCMacro
Corrections as requested...
---
=> [TD]correct version & remove debug prints

ParametricObjectCreation/honeycomb_solid/honeycomb_solid.py
Fix source typo tickness->thickness and some other trivial typos
=> honeycomb_solid.py: fix typos 

PureGui/Camera.FCMacro
- [X ] Please check this box if you're not submitting a new macro.   
---
=> [Camera] fix bad line split (l1335-6)

ImportExport/CadbaseLibrary.FCMacro, ImportExport/CadbaseLibrary/CdbsApi.py, ImportExport/CadbaseLibrary/CdbsAuth.py, ImportExport/CadbaseLibrary/DataHandler.py, ImportExport/CadbaseLibrary/README.md
---
@galou, unfortunately, I did not specify the files from the CadbaseLibrary folder with PR #144, and because of this, the macro did not run.
I apologize for making such a mistake, I fixed it here.
=> [CadbaseLibrary] Fixed bugs

ObjectCreation/BoxCreator.FCMacro
=> BoxCreator.FCMacro: fix broken syntax

Information/CenterOfMass.FCMacro
---
- **New**: Searchbar for solids
- **New**: Reworked import function to improve external bill of materials (BOM) import with better input tolerance
- **Fix**: Changed caption "weight" to "mass" in export file
- **Code**: Indentation of on_pushButton_Export() similar to on_pushButton_Import()
- **Code**: Idiomatic python
- **New**: Mass can be set zero to exclude solid from calculation and visualization
- **Fix**: Behaviour of default value spin and "Apply to all"
- **Fix**: Preserve original solids color when "New" button pressed
=> [CenterOfMass] Searchbar, BOM import, Zero mass, Fixes

Information/GetGlobalPlacement-test.txt, Information/GetGlobalPlacement.FCMacro
Include transformations made by App::Link that happens on top of Placement property if the link object is selected. That way the returned placement reflects the coordinate system used by the links content.
Added array link in test file
=> Some fixes for GetGlobalPlacement

ImportExport/CadbaseLibrary.FCMacro, ImportExport/CadbaseLibrary/CdbsApi.py, ImportExport/CadbaseLibrary/CdbsAuth.py, ImportExport/CadbaseLibrary/CdbsEvn.py, ImportExport/CadbaseLibrary/CdbsStorage.py, ImportExport/CadbaseLibrary/CdbsStorageApi.py, ImportExport/CadbaseLibrary/DataHandler.py, ImportExport/CadbaseLibrary/QueriesApi.py, ImportExport/CadbaseLibrary/README.md, ImportExport/CadbaseLibrary/cadbase_library.ui
---
Sorry for the long message in the first commit.
A video on how this macro works (02:20): https://youtu.be/ONtNrYrg3HU
=> [CadbaseLibrary] Update to v0.2.0: add functionality for uploading files

DatumPlaneLocalAxis.FCMacro, Std_DatumPlanelocalaxis.svg
---
DatumPlaneLocalAxis 
1.The macro will add small X, Y, and Z axis representations on the selected datum plane in the 3D view. The X-axis is represented in red, the Y-axis in green, and the Z-axis in blue.
2. To clear the axis representations, simply click on the macro again, and the representations will be removed.
=> macro for datum Plane local Axis

Information/CenterOfMass.FCMacro
---
- **New**: Added buttons for Copy to clipboard
- **New**: Scalable Vector Graphics icon
- **Fix**: Compatibility for FreeCAD versions and web revised
=> [CenterOfMass] Icon, copy to clipboard, compatibility

Information/CenterOfMass.FCMacro
---
- **Fix**: Make 0.22.0dev AssemblyExample work
- **Fix**: BOM Import containing custom material
- **Fix**: Support the new material cards
- **Fix**: Changed or missing icons, version checks
=> [CenterOfMass] Prepare for major FreeCAD release

ObjectCreation/BSpline3D.FCMacro
=> [BSpline3D] Make a parametric Draft BSpline in 3D from selected vertices

ObjectCreation/boxcreator/boxcreator.ui
And please remember to update the Wiki with the features added or changed once this PR is merged.
---
=> [BoxCreator] fixed form tab order
